// AUTO-GENERATED by scripts/gen-constellation.mjs — do not edit by hand.
// Shallow arch for narrow screens — same language, centre below the frame
// so only the crown of the circle shows. Arc 143°→37°, focal star idx 3.

import type { CSSProperties } from 'react'

export default function ConstellationCrown({ className }: { className?: string }) {
  return (
    <svg
      className={className}
      viewBox="0 0 760 340"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden="true"
      focusable="false"
    >
      <defs>
        <radialGradient id="oc-halo" cx="50%" cy="50%" r="50%">
          <stop offset="0%" stopColor="#FFD487" stopOpacity="1" />
          <stop offset="35%" stopColor="#D69338" stopOpacity="0.33" />
          <stop offset="100%" stopColor="#8B4D14" stopOpacity="0" />
        </radialGradient>
        <radialGradient id="oc-nucleus" cx="50%" cy="50%" r="50%">
          <stop offset="0%" stopColor="#FFF9E8" stopOpacity="0.9" />
          <stop offset="40%" stopColor="#F7E4A9" stopOpacity="0.38" />
          <stop offset="100%" stopColor="#E6BA4E" stopOpacity="0" />
        </radialGradient>
      </defs>

      <g className="oc-glow">
      </g>

      <g className="oc-depth" fill="none" strokeLinecap="round">
        <path d="M 111.75 140.07 A 400.9 400.9 0 0 1 179.55 90.81" stroke="#F0D07B" strokeWidth="0.7" opacity="0.095" />
        <path d="M 568.21 84.03 A 400.9 400.9 0 0 1 632.29 126.44" stroke="#F0D07B" strokeWidth="0.7" opacity="0.07" />
        <path d="M 222.58 115.24 A 359.1 359.1 0 0 1 293.13 89.57" stroke="#F0D07B" strokeWidth="0.65" opacity="0.08" />
        <path d="M 454.66 86.75 A 359.1 359.1 0 0 1 514.52 105.05" stroke="#F0D07B" strokeWidth="0.65" opacity="0.06" />
      </g>

      <g className="oc-dust">
        <circle cx="182.48" cy="79.74" r="0.75" fill="#E6BA4E" opacity="0.26" />
        <circle cx="732.17" cy="266.97" r="0.59" fill="#8A7C67" opacity="0.36" />
        <circle cx="415.39" cy="40.75" r="0.71" fill="#E6BA4E" opacity="0.25" />
        <circle cx="288.71" cy="92.65" r="0.56" fill="#E6BA4E" opacity="0.33" />
        <circle cx="302.5" cy="77.5" r="0.58" fill="#E6BA4E" opacity="0.15" />
        <circle cx="422.54" cy="18.26" r="0.73" fill="#8A7C67" opacity="0.38" />
        <circle cx="391.09" cy="123.66" r="0.81" fill="#8A7C67" opacity="0.33" />
        <circle cx="520.11" cy="121.11" r="0.85" fill="#E6BA4E" opacity="0.15" />
        <circle cx="99.39" cy="198.65" r="0.97" fill="#E6BA4E" opacity="0.37" />
        <circle cx="47.83" cy="174.15" r="1.03" fill="#E6BA4E" opacity="0.32" />
        <circle cx="680.32" cy="199.34" r="0.96" fill="#E6BA4E" opacity="0.34" />
        <circle cx="542.73" cy="134.86" r="0.76" fill="#E6BA4E" opacity="0.31" />
        <circle cx="141.57" cy="142.58" r="0.78" fill="#8A7C67" opacity="0.19" />
        <circle cx="583.62" cy="117.04" r="0.86" fill="#E6BA4E" opacity="0.28" />
        <circle cx="669.42" cy="252.42" r="0.51" fill="#E6BA4E" opacity="0.14" />
        <circle cx="365.64" cy="58.33" r="0.78" fill="#8A7C67" opacity="0.38" />
        <circle cx="281.1" cy="149.87" r="0.72" fill="#E6BA4E" opacity="0.21" />
        <circle cx="502.86" cy="114.53" r="0.76" fill="#E6BA4E" opacity="0.15" />
        <circle cx="587.22" cy="193.32" r="0.78" fill="#E6BA4E" opacity="0.23" />
        <circle cx="112.75" cy="100.74" r="0.98" fill="#E6BA4E" opacity="0.13" />
        <circle cx="98.36" cy="176.84" r="0.74" fill="#E6BA4E" opacity="0.32" />
        <circle cx="572.21" cy="46.29" r="0.88" fill="#E6BA4E" opacity="0.14" />
        <circle cx="615.01" cy="247.8" r="0.79" fill="#E6BA4E" opacity="0.21" />
        <circle cx="342.45" cy="114.8" r="0.72" fill="#E6BA4E" opacity="0.24" />
        <circle cx="99.81" cy="180.68" r="0.56" fill="#8A7C67" opacity="0.4" />
        <circle cx="690.03" cy="193.67" r="0.46" fill="#8A7C67" opacity="0.34" />
        <circle cx="591.74" cy="115.41" r="0.55" fill="#E6BA4E" opacity="0.2" />
        <circle cx="266.86" cy="74.69" r="0.66" fill="#E6BA4E" opacity="0.28" />
        <circle cx="525.06" cy="92.87" r="1.01" fill="#8A7C67" opacity="0.12" />
        <circle cx="332.92" cy="57.54" r="0.85" fill="#E6BA4E" opacity="0.34" />
        <circle cx="111.27" cy="147.39" r="0.77" fill="#E6BA4E" opacity="0.29" />
        <circle cx="565.76" cy="104.67" r="1.02" fill="#E6BA4E" opacity="0.36" />
        <circle cx="355.05" cy="101.96" r="0.75" fill="#8A7C67" opacity="0.37" />
        <circle cx="94.64" cy="187.16" r="0.6" fill="#8A7C67" opacity="0.34" />
        <circle cx="636.24" cy="167.59" r="0.48" fill="#E6BA4E" opacity="0.4" />
        <circle cx="157.87" cy="135.09" r="1.03" fill="#E6BA4E" opacity="0.17" />
        <circle cx="371.38" cy="10.65" r="1.02" fill="#8A7C67" opacity="0.12" />
        <circle cx="656.32" cy="176.88" r="0.62" fill="#E6BA4E" opacity="0.15" />
        <circle cx="743.64" cy="327.71" r="0.74" fill="#8A7C67" opacity="0.22" />
        <circle cx="75.82" cy="231.44" r="0.53" fill="#8A7C67" opacity="0.29" />
        <circle cx="303.7" cy="58.42" r="0.9" fill="#8A7C67" opacity="0.3" />
        <circle cx="143.39" cy="113.7" r="0.83" fill="#E6BA4E" opacity="0.14" />
        <circle cx="674.52" cy="196.94" r="0.84" fill="#8A7C67" opacity="0.15" />
        <circle cx="590.72" cy="195.07" r="0.94" fill="#E6BA4E" opacity="0.21" />
        <circle cx="414.51" cy="55.29" r="0.61" fill="#E6BA4E" opacity="0.29" />
        <circle cx="216.89" cy="104.06" r="0.97" fill="#8A7C67" opacity="0.13" />
        <circle cx="739.06" cy="313.58" r="0.59" fill="#E6BA4E" opacity="0.2" />
        <circle cx="435.67" cy="91.73" r="0.75" fill="#E6BA4E" opacity="0.4" />
        <circle cx="70.84" cy="208.56" r="0.8" fill="#8A7C67" opacity="0.26" />
        <circle cx="463.47" cy="88.92" r="0.54" fill="#8A7C67" opacity="0.31" />
        <circle cx="514.77" cy="68.72" r="0.46" fill="#E6BA4E" opacity="0.29" />
        <circle cx="628.17" cy="158.26" r="0.97" fill="#E6BA4E" opacity="0.23" />
        <circle cx="728.05" cy="285.4" r="0.81" fill="#E6BA4E" opacity="0.36" />
        <circle cx="185.98" cy="111.35" r="0.91" fill="#8A7C67" opacity="0.27" />
        <circle cx="296.72" cy="78.49" r="0.74" fill="#E6BA4E" opacity="0.25" />
        <circle cx="722.3" cy="273.84" r="0.53" fill="#E6BA4E" opacity="0.3" />
        <circle cx="326.98" cy="83.2" r="0.81" fill="#8A7C67" opacity="0.21" />
        <circle cx="196.52" cy="105.24" r="0.57" fill="#E6BA4E" opacity="0.24" />
        <circle cx="102.07" cy="178.86" r="0.82" fill="#E6BA4E" opacity="0.3" />
        <circle cx="693.94" cy="244.29" r="0.48" fill="#8A7C67" opacity="0.21" />
        <circle cx="98.15" cy="172.03" r="0.48" fill="#E6BA4E" opacity="0.16" />
        <circle cx="649.9" cy="162.54" r="0.93" fill="#8A7C67" opacity="0.35" />
        <circle cx="642.1" cy="193.59" r="0.7" fill="#E6BA4E" opacity="0.34" />
        <circle cx="648.92" cy="58.76" r="0.81" fill="#E6BA4E" opacity="0.3" />
        <circle cx="29.95" cy="163.77" r="0.92" fill="#E6BA4E" opacity="0.23" />
        <circle cx="569.9" cy="77.05" r="0.87" fill="#8A7C67" opacity="0.38" />
        <circle cx="608.48" cy="130.94" r="0.83" fill="#E6BA4E" opacity="0.28" />
        <circle cx="654.34" cy="93.99" r="0.64" fill="#E6BA4E" opacity="0.17" />
        <circle cx="341.47" cy="131.24" r="0.55" fill="#8A7C67" opacity="0.38" />
        <circle cx="689" cy="216.52" r="0.48" fill="#E6BA4E" opacity="0.16" />
        <circle cx="152.89" cy="88.81" r="0.57" fill="#E6BA4E" opacity="0.28" />
        <circle cx="486.74" cy="73.3" r="0.98" fill="#8A7C67" opacity="0.31" />
        <circle cx="129.7" cy="169.13" r="1.01" fill="#8A7C67" opacity="0.12" />
        <circle cx="284.05" cy="71.94" r="0.61" fill="#E6BA4E" opacity="0.22" />
        <circle cx="95.04" cy="180.39" r="0.71" fill="#E6BA4E" opacity="0.13" />
        <circle cx="369.7" cy="56.03" r="0.68" fill="#E6BA4E" opacity="0.29" />
        <circle cx="32.09" cy="254.93" r="0.87" fill="#E6BA4E" opacity="0.15" />
        <circle cx="373.1" cy="52.47" r="0.67" fill="#8A7C67" opacity="0.32" />
        <circle cx="640.45" cy="213.79" r="0.83" fill="#E6BA4E" opacity="0.33" />
        <circle cx="553.59" cy="99.97" r="0.78" fill="#8A7C67" opacity="0.28" />
        <circle cx="729.29" cy="224.9" r="0.82" fill="#8A7C67" opacity="0.36" />
        <circle cx="357.31" cy="103.39" r="0.96" fill="#8A7C67" opacity="0.2" />
        <circle cx="378.14" cy="68.02" r="1.02" fill="#8A7C67" opacity="0.4" />
        <circle cx="671.26" cy="228.29" r="0.9" fill="#E6BA4E" opacity="0.36" />
        <circle cx="650.37" cy="307.89" r="0.63" fill="#E6BA4E" opacity="0.21" />
        <circle cx="501.53" cy="102.21" r="0.53" fill="#E6BA4E" opacity="0.14" />
        <circle cx="308.12" cy="64.83" r="0.52" fill="#E6BA4E" opacity="0.19" />
        <circle cx="423.75" cy="86.39" r="0.57" fill="#8A7C67" opacity="0.27" />
        <circle cx="106.28" cy="248.12" r="1.02" fill="#8A7C67" opacity="0.2" />
        <circle cx="413.91" cy="114.48" r="0.74" fill="#8A7C67" opacity="0.23" />
        <circle cx="14.79" cy="238.21" r="0.92" fill="#8A7C67" opacity="0.4" />
        <circle cx="679.28" cy="195.83" r="0.93" fill="#E6BA4E" opacity="0.24" />
        <circle cx="41.57" cy="293.75" r="0.68" fill="#E6BA4E" opacity="0.26" />
        <circle cx="506.76" cy="47.97" r="0.78" fill="#E6BA4E" opacity="0.33" />
        <circle cx="544.97" cy="82.54" r="0.7" fill="#8A7C67" opacity="0.16" />
        <circle cx="287.47" cy="49.46" r="1.04" fill="#8A7C67" opacity="0.18" />
        <circle cx="566.72" cy="75.18" r="0.93" fill="#E6BA4E" opacity="0.23" />
        <circle cx="255.48" cy="179.3" r="1.1" fill="#8A7C67" opacity="0.31" />
        <circle cx="114.72" cy="207.44" r="0.48" fill="#E6BA4E" opacity="0.15" />
        <circle cx="144.87" cy="231.16" r="0.41" fill="#6D604E" opacity="0.18" />
        <circle cx="370.24" cy="173.72" r="0.36" fill="#8A7C67" opacity="0.23" />
        <circle cx="643.9" cy="32.85" r="0.49" fill="#6D604E" opacity="0.18" />
        <circle cx="176.86" cy="153.31" r="0.81" fill="#8A7C67" opacity="0.17" />
        <circle cx="235.51" cy="31.3" r="0.96" fill="#8A7C67" opacity="0.22" />
        <circle cx="371.53" cy="139.61" r="0.48" fill="#E6BA4E" opacity="0.19" />
        <circle cx="484.34" cy="244.35" r="0.48" fill="#8A7C67" opacity="0.24" />
        <circle cx="450.76" cy="276.84" r="0.71" fill="#6D604E" opacity="0.33" />
        <circle cx="361.54" cy="27.32" r="1.12" fill="#8A7C67" opacity="0.26" />
        <circle cx="597.47" cy="167.14" r="0.88" fill="#E6BA4E" opacity="0.39" />
        <circle cx="626.43" cy="238.29" r="0.52" fill="#6D604E" opacity="0.24" />
        <circle cx="376.27" cy="252.78" r="0.69" fill="#E6BA4E" opacity="0.39" />
        <circle cx="264.07" cy="42.83" r="0.47" fill="#E6BA4E" opacity="0.2" />
        <circle cx="192.51" cy="178.21" r="0.65" fill="#6D604E" opacity="0.4" />
        <circle cx="377.88" cy="322.96" r="1.12" fill="#E6BA4E" opacity="0.28" />
        <circle cx="295.67" cy="277.86" r="1.04" fill="#8A7C67" opacity="0.23" />
        <circle cx="702.94" cy="275.11" r="0.69" fill="#6D604E" opacity="0.31" />
        <circle cx="152.42" cy="239.96" r="0.72" fill="#E6BA4E" opacity="0.29" />
        <circle cx="440.56" cy="88.92" r="0.97" fill="#8A7C67" opacity="0.2" />
        <circle cx="465.31" cy="135.78" r="0.55" fill="#8A7C67" opacity="0.22" />
        <circle cx="657.54" cy="241.68" r="0.5" fill="#E6BA4E" opacity="0.18" />
        <circle cx="387.32" cy="271.74" r="1.14" fill="#8A7C67" opacity="0.18" />
        <circle cx="97.75" cy="284.55" r="0.65" fill="#8A7C67" opacity="0.32" />
        <circle cx="652.89" cy="64.74" r="0.79" fill="#E6BA4E" opacity="0.36" />
        <circle cx="510.39" cy="186.22" r="0.79" fill="#E6BA4E" opacity="0.16" />
        <circle cx="183.87" cy="303.5" r="1.11" fill="#E6BA4E" opacity="0.3" />
        <circle cx="31.01" cy="181.52" r="0.74" fill="#6D604E" opacity="0.41" />
        <circle cx="234.45" cy="32.66" r="0.95" fill="#8A7C67" opacity="0.33" />
        <circle cx="170.46" cy="82.46" r="0.44" fill="#6D604E" opacity="0.19" />
        <circle cx="517.7" cy="183.94" r="1" fill="#8A7C67" opacity="0.32" />
        <circle cx="155.8" cy="229.75" r="1.02" fill="#E6BA4E" opacity="0.22" />
        <circle cx="414.62" cy="141.07" r="0.38" fill="#6D604E" opacity="0.19" />
        <circle cx="169.93" cy="210.06" r="1.12" fill="#6D604E" opacity="0.32" />
        <circle cx="329.86" cy="25.15" r="0.78" fill="#8A7C67" opacity="0.38" />
        <circle cx="591.62" cy="249.65" r="0.54" fill="#6D604E" opacity="0.14" />
        <circle cx="620.47" cy="262.22" r="0.9" fill="#6D604E" opacity="0.39" />
        <circle cx="610.17" cy="203.82" r="0.72" fill="#E6BA4E" opacity="0.36" />
        <circle cx="604.68" cy="261.47" r="0.55" fill="#8A7C67" opacity="0.23" />
        <circle cx="682.96" cy="45.69" r="0.82" fill="#E6BA4E" opacity="0.18" />
        <circle cx="502.72" cy="216.12" r="0.41" fill="#8A7C67" opacity="0.24" />
        <circle cx="164.61" cy="175.97" r="0.86" fill="#6D604E" opacity="0.18" />
      </g>

      <g className="oc-arcs" fill="none" stroke="#F0D07B" strokeWidth="0.9" strokeLinecap="round">
        <path d="M 82.74 194.76 A 384.1 384.1 0 0 1 103.76 171.12" opacity="0.31" />
        <path d="M 130.57 151.4 A 379.94 379.94 0 0 1 157.91 129.73" opacity="0.35" />
        <path d="M 199.03 107.73 A 376.6 376.6 0 0 1 249.72 84.65" opacity="0.36" />
        <path d="M 293.49 71.4 A 376.66 376.66 0 0 1 334.26 64.12" opacity="0.37" />
        <path d="M 375.05 61.27 A 376.77 376.77 0 0 1 405.02 62.07" opacity="0.32" />
        <path d="M 439.72 60.72 A 381.98 381.98 0 0 1 465.14 65.63" opacity="0.32" />
        <path d="M 502.67 74.53 A 383.61 383.61 0 0 1 552.59 95.4" opacity="0.19" />
        <path d="M 657.41 182.31 A 377.27 377.27 0 0 1 671.8 198.87" opacity="0.1" />
      </g>

      <g className="oc-stars">
        <g className="oc-star oc-star--quiet" style={{ '--oc-i': 0, '--oc-d': '10.48s' } as CSSProperties}>
          <g opacity="0.75">
            <ellipse cx="78.05" cy="210.47" rx="5.54" ry="3.38" fill="url(#oc-halo)" opacity="0.31" />
            <ellipse cx="77.98" cy="209.76" rx="3.43" ry="2.21" fill="url(#oc-halo)" opacity="0.37" />
            <ellipse cx="77.85" cy="209.88" rx="1.45" ry="0.97" fill="url(#oc-halo)" opacity="0.54" />
            <circle cx="78.05" cy="210.47" r="2.72" fill="url(#oc-nucleus)" opacity="0.73" />
          </g>
        </g>
        <g className="oc-star oc-star--quiet" style={{ '--oc-i': 1, '--oc-d': '9.32s' } as CSSProperties}>
          <g opacity="0.84">
            <ellipse cx="110.5" cy="155.93" rx="3.58" ry="2.18" fill="url(#oc-halo)" opacity="0.31" />
            <ellipse cx="110.76" cy="155.65" rx="2.22" ry="1.43" fill="url(#oc-halo)" opacity="0.37" />
            <ellipse cx="110.21" cy="155.89" rx="0.94" ry="0.63" fill="url(#oc-halo)" opacity="0.54" />
            <circle cx="110.5" cy="155.93" r="1.76" fill="url(#oc-nucleus)" opacity="0.9" />
            <circle cx="113.86" cy="147.44" r="0.73" fill="#F0D07B" opacity="0.28" />
          </g>
        </g>
        <g className="oc-star oc-star--quiet" style={{ '--oc-i': 2, '--oc-d': '8.37s' } as CSSProperties}>
          <g opacity="0.92">
            <ellipse cx="178.01" cy="128.28" rx="5.82" ry="3.55" fill="url(#oc-halo)" opacity="0.31" />
            <ellipse cx="178.43" cy="128.97" rx="3.6" ry="2.32" fill="url(#oc-halo)" opacity="0.37" />
            <ellipse cx="177.89" cy="128.11" rx="1.52" ry="1.02" fill="url(#oc-halo)" opacity="0.54" />
            <circle cx="178.01" cy="128.28" r="2.86" fill="url(#oc-nucleus)" opacity="0.9" />
          </g>
        </g>
        <g className="oc-star oc-star--focal" style={{ '--oc-i': 3, '--oc-d': '7.95s' } as CSSProperties}>
          <g opacity="1">
            <ellipse cx="275.29" cy="69.13" rx="34.02" ry="20.74" fill="url(#oc-halo)" opacity="0.61" />
            <ellipse cx="276.59" cy="70.14" rx="21.06" ry="13.56" fill="url(#oc-halo)" opacity="0.73" />
            <ellipse cx="273.18" cy="67.22" rx="8.91" ry="5.98" fill="url(#oc-halo)" opacity="1" />
            <circle cx="275.29" cy="69.13" r="5.94" fill="url(#oc-nucleus)" opacity="1" />
          </g>
        </g>
        <g className="oc-star oc-star--quiet" style={{ '--oc-i': 4, '--oc-d': '8.97s' } as CSSProperties}>
          <g opacity="0.92">
            <ellipse cx="351.59" cy="69.2" rx="6.05" ry="3.69" fill="url(#oc-halo)" opacity="0.31" />
            <ellipse cx="351.45" cy="68.71" rx="3.75" ry="2.41" fill="url(#oc-halo)" opacity="0.37" />
            <ellipse cx="351.78" cy="68.68" rx="1.58" ry="1.06" fill="url(#oc-halo)" opacity="0.54" />
            <circle cx="351.59" cy="69.2" r="2.97" fill="url(#oc-nucleus)" opacity="0.88" />
            <circle cx="360.69" cy="75.9" r="0.53" fill="#F0D07B" opacity="0.3" />
          </g>
        </g>
        <g className="oc-star oc-star--quiet" style={{ '--oc-i': 5, '--oc-d': '6.8s' } as CSSProperties}>
          <g opacity="0.84">
            <ellipse cx="429.8" cy="57.6" rx="4.78" ry="2.92" fill="url(#oc-halo)" opacity="0.31" />
            <ellipse cx="430.02" cy="57.79" rx="2.96" ry="1.91" fill="url(#oc-halo)" opacity="0.37" />
            <ellipse cx="429.55" cy="57.71" rx="1.25" ry="0.84" fill="url(#oc-halo)" opacity="0.54" />
            <circle cx="429.8" cy="57.6" r="2.35" fill="url(#oc-nucleus)" opacity="0.88" />
          </g>
        </g>
        <g className="oc-star oc-star--quiet" style={{ '--oc-i': 6, '--oc-d': '10.44s' } as CSSProperties}>
          <g opacity="0.75">
            <ellipse cx="474.67" cy="69.65" rx="4.85" ry="2.96" fill="url(#oc-halo)" opacity="0.31" />
            <ellipse cx="474.57" cy="69.16" rx="3" ry="1.93" fill="url(#oc-halo)" opacity="0.37" />
            <ellipse cx="474.52" cy="69.99" rx="1.27" ry="0.85" fill="url(#oc-halo)" opacity="0.54" />
            <circle cx="474.67" cy="69.65" r="2.38" fill="url(#oc-nucleus)" opacity="0.62" />
            <circle cx="471.5" cy="65.07" r="0.74" fill="#F0D07B" opacity="0.39" />
          </g>
        </g>
        <g className="oc-star oc-star--second" style={{ '--oc-i': 7, '--oc-d': '8.62s' } as CSSProperties}>
          <g opacity="0.66">
            <ellipse cx="579.11" cy="106.26" rx="16.63" ry="10.14" fill="url(#oc-halo)" opacity="0.47" />
            <ellipse cx="577.67" cy="104.84" rx="10.3" ry="6.63" fill="url(#oc-halo)" opacity="0.56" />
            <ellipse cx="579.15" cy="105.83" rx="4.36" ry="2.93" fill="url(#oc-halo)" opacity="0.83" />
            <circle cx="579.11" cy="106.26" r="3.28" fill="url(#oc-nucleus)" opacity="1" />
          </g>
        </g>
        <g className="oc-star oc-star--quiet" style={{ '--oc-i': 8, '--oc-d': '6.43s' } as CSSProperties}>
          <g opacity="0.54">
            <ellipse cx="649.58" cy="168.4" rx="5.26" ry="3.21" fill="url(#oc-halo)" opacity="0.31" />
            <ellipse cx="649.63" cy="168.18" rx="3.26" ry="2.1" fill="url(#oc-halo)" opacity="0.37" />
            <ellipse cx="649.5" cy="169.07" rx="1.38" ry="0.93" fill="url(#oc-halo)" opacity="0.54" />
            <circle cx="649.58" cy="168.4" r="2.58" fill="url(#oc-nucleus)" opacity="0.71" />
          </g>
        </g>
        <g className="oc-star oc-star--quiet" style={{ '--oc-i': 9, '--oc-d': '10.22s' } as CSSProperties}>
          <g opacity="0.36">
            <ellipse cx="678.12" cy="213.35" rx="3.19" ry="1.95" fill="url(#oc-halo)" opacity="0.31" />
            <ellipse cx="678.2" cy="213.18" rx="1.98" ry="1.27" fill="url(#oc-halo)" opacity="0.37" />
            <ellipse cx="678.17" cy="213.66" rx="0.84" ry="0.56" fill="url(#oc-halo)" opacity="0.54" />
            <circle cx="678.12" cy="213.35" r="1.57" fill="url(#oc-nucleus)" opacity="0.65" />
          </g>
        </g>
      </g>
    </svg>
  )
}
