// AUTO-GENERATED by scripts/gen-constellation.mjs — do not edit by hand.
// The bowl, drawn at window scale on wide screens — arc 206°→6°,
// R = 0.40·min(w,h), cy = 0.52h, focal star idx 5. Sized in vh/vw and
// cropped by the viewport, so it frames the window rather than the headline.

import type { CSSProperties } from 'react'

export default function SkyHalo({ className }: { className?: string }) {
  return (
    <svg
      className={className}
      viewBox="0 0 690 560"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden="true"
      focusable="false"
    >
      <defs>
        <radialGradient id="oh-g0" cx="50%" cy="50%" r="50%">
          <stop offset="0%" stopColor="#E6BA4E" stopOpacity="0.13" />
          <stop offset="48%" stopColor="#E6BA4E" stopOpacity="0.04" />
          <stop offset="100%" stopColor="#E6BA4E" stopOpacity="0" />
        </radialGradient>
        <radialGradient id="oh-g1" cx="50%" cy="50%" r="50%">
          <stop offset="0%" stopColor="#F0D07B" stopOpacity="0.105" />
          <stop offset="48%" stopColor="#F0D07B" stopOpacity="0.04" />
          <stop offset="100%" stopColor="#F0D07B" stopOpacity="0" />
        </radialGradient>
        <radialGradient id="oh-g2" cx="50%" cy="50%" r="50%">
          <stop offset="0%" stopColor="#E6BA4E" stopOpacity="0.055" />
          <stop offset="48%" stopColor="#E6BA4E" stopOpacity="0.02" />
          <stop offset="100%" stopColor="#E6BA4E" stopOpacity="0" />
        </radialGradient>
        <radialGradient id="oh-h-quiet" cx="50%" cy="50%" r="50%">
          <stop offset="0%" stopColor="#F7E4A9" stopOpacity="0.24" />
          <stop offset="40%" stopColor="#E6BA4E" stopOpacity="0.07" />
          <stop offset="100%" stopColor="#E6BA4E" stopOpacity="0" />
        </radialGradient>
        <radialGradient id="oh-h-second" cx="50%" cy="50%" r="50%">
          <stop offset="0%" stopColor="#F7E4A9" stopOpacity="0.4" />
          <stop offset="40%" stopColor="#E6BA4E" stopOpacity="0.12" />
          <stop offset="100%" stopColor="#E6BA4E" stopOpacity="0" />
        </radialGradient>
        <radialGradient id="oh-h-focal" cx="50%" cy="50%" r="50%">
          <stop offset="0%" stopColor="#F7E4A9" stopOpacity="0.62" />
          <stop offset="40%" stopColor="#E6BA4E" stopOpacity="0.2" />
          <stop offset="100%" stopColor="#E6BA4E" stopOpacity="0" />
        </radialGradient>
      </defs>

      <g className="oc-glow">
        <ellipse cx="345" cy="296" rx="300" ry="258" fill="url(#oh-g0)" />
        <ellipse cx="205" cy="170" rx="195" ry="165" fill="url(#oh-g1)" />
        <ellipse cx="448" cy="372" rx="236" ry="186" fill="url(#oh-g2)" />
      </g>

      <g className="oc-depth" fill="none" strokeLinecap="round">
        <path d="M 99.2 274.01 A 246.4 246.4 0 0 1 103.13 244.18" stroke="#F0D07B" strokeWidth="0.6" opacity="0.075" />
        <path d="M 153.51 136.14 A 246.4 246.4 0 0 1 170.77 116.97" stroke="#F0D07B" strokeWidth="0.6" opacity="0.06" />
        <path d="M 468.2 77.81 A 246.4 246.4 0 0 1 486.33 89.36" stroke="#F0D07B" strokeWidth="0.6" opacity="0.045" />
        <path d="M 160.16 216.52 A 199.36 199.36 0 0 1 168.98 197.61" stroke="#8A7C67" strokeWidth="0.55" opacity="0.055" />
        <path d="M 283.39 101.6 A 199.36 199.36 0 0 1 300.15 96.95" stroke="#8A7C67" strokeWidth="0.55" opacity="0.04" />
      </g>

      <g className="oc-dust">
        <circle cx="547.07" cy="119.28" r="0.67" fill="#8A7C67" opacity="0.17" />
        <circle cx="515.31" cy="77.87" r="0.79" fill="#E6BA4E" opacity="0.25" />
        <circle cx="530.66" cy="223.68" r="0.87" fill="#8A7C67" opacity="0.21" />
        <circle cx="139.57" cy="201.89" r="1.05" fill="#8A7C67" opacity="0.38" />
        <circle cx="206.3" cy="113.96" r="0.9" fill="#8A7C67" opacity="0.2" />
        <circle cx="174.69" cy="123.61" r="0.58" fill="#E6BA4E" opacity="0.23" />
        <circle cx="589.45" cy="290.6" r="0.79" fill="#E6BA4E" opacity="0.33" />
        <circle cx="255.06" cy="82.94" r="0.51" fill="#8A7C67" opacity="0.23" />
        <circle cx="136.66" cy="372.92" r="0.49" fill="#E6BA4E" opacity="0.4" />
        <circle cx="85.36" cy="259.94" r="0.77" fill="#E6BA4E" opacity="0.13" />
        <circle cx="168.48" cy="430.15" r="0.48" fill="#8A7C67" opacity="0.19" />
        <circle cx="467.01" cy="103.3" r="0.88" fill="#E6BA4E" opacity="0.3" />
        <circle cx="524.82" cy="157.59" r="0.5" fill="#E6BA4E" opacity="0.3" />
        <circle cx="508.57" cy="144.33" r="0.47" fill="#E6BA4E" opacity="0.36" />
        <circle cx="553.64" cy="215.52" r="0.93" fill="#E6BA4E" opacity="0.16" />
        <circle cx="549.8" cy="206.63" r="0.9" fill="#E6BA4E" opacity="0.34" />
        <circle cx="556.4" cy="262.36" r="0.72" fill="#8A7C67" opacity="0.17" />
        <circle cx="379.21" cy="69.82" r="0.68" fill="#8A7C67" opacity="0.25" />
        <circle cx="121.3" cy="279.54" r="0.51" fill="#8A7C67" opacity="0.16" />
        <circle cx="418.66" cy="44.95" r="0.85" fill="#8A7C67" opacity="0.33" />
        <circle cx="553.66" cy="210.36" r="0.71" fill="#8A7C67" opacity="0.24" />
        <circle cx="197.25" cy="122.37" r="0.46" fill="#8A7C67" opacity="0.13" />
        <circle cx="268.47" cy="86.92" r="0.77" fill="#E6BA4E" opacity="0.16" />
        <circle cx="356.11" cy="65.69" r="0.81" fill="#E6BA4E" opacity="0.19" />
        <circle cx="557.64" cy="309.76" r="0.64" fill="#E6BA4E" opacity="0.16" />
        <circle cx="450.27" cy="89.77" r="0.76" fill="#E6BA4E" opacity="0.14" />
        <circle cx="125.19" cy="244.88" r="0.99" fill="#8A7C67" opacity="0.27" />
        <circle cx="150.33" cy="463.9" r="0.7" fill="#E6BA4E" opacity="0.27" />
        <circle cx="535.05" cy="218.47" r="0.85" fill="#E6BA4E" opacity="0.33" />
        <circle cx="146.14" cy="187.82" r="0.55" fill="#8A7C67" opacity="0.33" />
        <circle cx="567.92" cy="235.75" r="0.5" fill="#8A7C67" opacity="0.38" />
        <circle cx="557.31" cy="266.68" r="0.93" fill="#8A7C67" opacity="0.35" />
        <circle cx="287.42" cy="80.76" r="0.92" fill="#8A7C67" opacity="0.28" />
        <circle cx="124.84" cy="330.86" r="0.77" fill="#8A7C67" opacity="0.2" />
        <circle cx="618.87" cy="282.23" r="0.58" fill="#E6BA4E" opacity="0.27" />
        <circle cx="131.51" cy="393.62" r="0.58" fill="#8A7C67" opacity="0.15" />
        <circle cx="448.88" cy="92.62" r="1" fill="#E6BA4E" opacity="0.37" />
        <circle cx="150.83" cy="381.33" r="0.69" fill="#E6BA4E" opacity="0.26" />
        <circle cx="121.08" cy="285.32" r="0.52" fill="#E6BA4E" opacity="0.35" />
        <circle cx="576.21" cy="267.17" r="0.6" fill="#8A7C67" opacity="0.18" />
        <circle cx="542.54" cy="185.59" r="1" fill="#8A7C67" opacity="0.23" />
        <circle cx="367.85" cy="55.83" r="0.96" fill="#8A7C67" opacity="0.39" />
        <circle cx="563.66" cy="288.98" r="0.57" fill="#E6BA4E" opacity="0.13" />
        <circle cx="418.1" cy="74.9" r="0.51" fill="#8A7C67" opacity="0.2" />
        <circle cx="110.62" cy="248.13" r="0.82" fill="#E6BA4E" opacity="0.3" />
        <circle cx="569.36" cy="298.21" r="1" fill="#E6BA4E" opacity="0.16" />
        <circle cx="361.29" cy="67.79" r="0.85" fill="#8A7C67" opacity="0.37" />
        <circle cx="556.39" cy="206.75" r="0.9" fill="#8A7C67" opacity="0.19" />
        <circle cx="170.62" cy="368.11" r="0.82" fill="#8A7C67" opacity="0.19" />
        <circle cx="140.64" cy="383.69" r="0.89" fill="#8A7C67" opacity="0.33" />
        <circle cx="515.64" cy="78.86" r="0.54" fill="#8A7C67" opacity="0.24" />
        <circle cx="357.63" cy="59.58" r="0.86" fill="#8A7C67" opacity="0.38" />
        <circle cx="166.91" cy="269.6" r="0.58" fill="#8A7C67" opacity="0.2" />
        <circle cx="410.04" cy="77.02" r="0.9" fill="#8A7C67" opacity="0.28" />
        <circle cx="354.77" cy="72.93" r="1.03" fill="#8A7C67" opacity="0.4" />
        <circle cx="212.48" cy="72.7" r="0.75" fill="#8A7C67" opacity="0.29" />
        <circle cx="537.04" cy="145.82" r="0.72" fill="#E6BA4E" opacity="0.38" />
        <circle cx="332.68" cy="60.68" r="0.78" fill="#E6BA4E" opacity="0.31" />
        <circle cx="153.22" cy="390.38" r="0.54" fill="#E6BA4E" opacity="0.35" />
        <circle cx="83.3" cy="354.94" r="1.02" fill="#8A7C67" opacity="0.39" />
        <circle cx="520.01" cy="154.61" r="0.94" fill="#8A7C67" opacity="0.22" />
        <circle cx="565.43" cy="327.97" r="0.73" fill="#E6BA4E" opacity="0.3" />
        <circle cx="213.46" cy="138.09" r="0.63" fill="#8A7C67" opacity="0.31" />
        <circle cx="565.33" cy="313.45" r="0.71" fill="#E6BA4E" opacity="0.3" />
        <circle cx="252.02" cy="130.96" r="0.76" fill="#8A7C67" opacity="0.39" />
        <circle cx="338.37" cy="95.6" r="0.62" fill="#8A7C67" opacity="0.14" />
        <circle cx="142.24" cy="175.78" r="0.55" fill="#8A7C67" opacity="0.3" />
        <circle cx="123.13" cy="321.51" r="0.77" fill="#8A7C67" opacity="0.34" />
        <circle cx="562.31" cy="348.05" r="1.05" fill="#8A7C67" opacity="0.36" />
        <circle cx="466.47" cy="47.75" r="0.55" fill="#E6BA4E" opacity="0.15" />
        <circle cx="565.3" cy="226.74" r="0.45" fill="#E6BA4E" opacity="0.19" />
        <circle cx="177.61" cy="470.34" r="0.56" fill="#E6BA4E" opacity="0.18" />
        <circle cx="84.62" cy="259.84" r="0.98" fill="#8A7C67" opacity="0.22" />
        <circle cx="217.66" cy="63.28" r="0.63" fill="#E6BA4E" opacity="0.34" />
        <circle cx="438.86" cy="44.14" r="1.03" fill="#E6BA4E" opacity="0.13" />
        <circle cx="497.38" cy="140.16" r="0.76" fill="#8A7C67" opacity="0.39" />
        <circle cx="165.11" cy="345.2" r="0.95" fill="#E6BA4E" opacity="0.23" />
        <circle cx="552.17" cy="141.94" r="0.72" fill="#E6BA4E" opacity="0.23" />
        <circle cx="526.17" cy="184.37" r="0.53" fill="#E6BA4E" opacity="0.33" />
        <circle cx="135.65" cy="233.17" r="0.92" fill="#E6BA4E" opacity="0.29" />
        <circle cx="131.94" cy="223.89" r="0.67" fill="#8A7C67" opacity="0.36" />
        <circle cx="568.87" cy="298.71" r="0.8" fill="#8A7C67" opacity="0.24" />
        <circle cx="121.93" cy="276.97" r="0.76" fill="#8A7C67" opacity="0.17" />
        <circle cx="418.27" cy="79.33" r="0.53" fill="#8A7C67" opacity="0.19" />
        <circle cx="474.88" cy="110.22" r="0.94" fill="#E6BA4E" opacity="0.15" />
        <circle cx="135.07" cy="369.55" r="0.7" fill="#8A7C67" opacity="0.19" />
        <circle cx="141.04" cy="366.15" r="0.6" fill="#E6BA4E" opacity="0.15" />
        <circle cx="492.78" cy="58.87" r="1.03" fill="#E6BA4E" opacity="0.37" />
        <circle cx="255.44" cy="96.78" r="0.7" fill="#E6BA4E" opacity="0.36" />
        <circle cx="127.11" cy="364.54" r="0.47" fill="#8A7C67" opacity="0.28" />
        <circle cx="178.41" cy="102.35" r="0.99" fill="#8A7C67" opacity="0.32" />
        <circle cx="192.41" cy="119.69" r="0.76" fill="#8A7C67" opacity="0.23" />
        <circle cx="432.22" cy="113.13" r="0.53" fill="#E6BA4E" opacity="0.26" />
        <circle cx="162.17" cy="403.54" r="1.02" fill="#E6BA4E" opacity="0.37" />
        <circle cx="125.31" cy="247.45" r="0.54" fill="#E6BA4E" opacity="0.38" />
        <circle cx="109.84" cy="296.06" r="0.61" fill="#E6BA4E" opacity="0.34" />
        <circle cx="457.86" cy="97.97" r="0.68" fill="#E6BA4E" opacity="0.16" />
        <circle cx="199.21" cy="97.82" r="0.59" fill="#8A7C67" opacity="0.38" />
        <circle cx="341.66" cy="44.52" r="0.77" fill="#8A7C67" opacity="0.22" />
        <circle cx="110.91" cy="338.57" r="0.46" fill="#E6BA4E" opacity="0.15" />
        <circle cx="583.35" cy="318.18" r="0.91" fill="#8A7C67" opacity="0.34" />
        <circle cx="174.63" cy="333.34" r="0.74" fill="#E6BA4E" opacity="0.22" />
        <circle cx="273.79" cy="76.89" r="1.02" fill="#8A7C67" opacity="0.3" />
        <circle cx="417.12" cy="81.33" r="0.5" fill="#E6BA4E" opacity="0.17" />
        <circle cx="590.4" cy="296.74" r="0.85" fill="#E6BA4E" opacity="0.17" />
        <circle cx="218.32" cy="110.32" r="0.83" fill="#E6BA4E" opacity="0.19" />
        <circle cx="390.71" cy="93.65" r="0.98" fill="#8A7C67" opacity="0.18" />
        <circle cx="546.06" cy="202.43" r="0.83" fill="#8A7C67" opacity="0.28" />
        <circle cx="169.22" cy="108.99" r="0.78" fill="#E6BA4E" opacity="0.35" />
        <circle cx="410.59" cy="77.02" r="0.89" fill="#8A7C67" opacity="0.14" />
        <circle cx="124.4" cy="330.05" r="0.61" fill="#8A7C67" opacity="0.33" />
        <circle cx="414.68" cy="73.2" r="0.94" fill="#8A7C67" opacity="0.37" />
        <circle cx="90.26" cy="315.16" r="0.54" fill="#8A7C67" opacity="0.28" />
        <circle cx="516.4" cy="152.25" r="0.6" fill="#8A7C67" opacity="0.21" />
        <circle cx="528.3" cy="162.44" r="0.64" fill="#8A7C67" opacity="0.15" />
        <circle cx="504.6" cy="133.48" r="0.83" fill="#8A7C67" opacity="0.25" />
        <circle cx="396.49" cy="73.17" r="0.64" fill="#E6BA4E" opacity="0.33" />
        <circle cx="566.99" cy="318.79" r="0.95" fill="#E6BA4E" opacity="0.22" />
        <circle cx="357.96" cy="105.29" r="0.83" fill="#E6BA4E" opacity="0.26" />
        <circle cx="567.65" cy="266.59" r="0.51" fill="#8A7C67" opacity="0.13" />
        <circle cx="525.59" cy="133.6" r="0.89" fill="#E6BA4E" opacity="0.3" />
        <circle cx="15.23" cy="228.76" r="1.1" fill="#8A7C67" opacity="0.2" />
        <circle cx="81.67" cy="30.33" r="0.74" fill="#6D604E" opacity="0.32" />
        <circle cx="287.81" cy="41.59" r="1.08" fill="#8A7C67" opacity="0.36" />
        <circle cx="510.53" cy="492.94" r="0.99" fill="#E6BA4E" opacity="0.34" />
        <circle cx="341.53" cy="89.15" r="0.58" fill="#6D604E" opacity="0.15" />
        <circle cx="105.51" cy="200.5" r="0.53" fill="#8A7C67" opacity="0.1" />
        <circle cx="91.78" cy="273.7" r="0.81" fill="#E6BA4E" opacity="0.42" />
        <circle cx="316.15" cy="382.05" r="1.11" fill="#8A7C67" opacity="0.28" />
        <circle cx="78.8" cy="125.52" r="1.06" fill="#E6BA4E" opacity="0.18" />
        <circle cx="237.01" cy="36.47" r="0.49" fill="#6D604E" opacity="0.12" />
        <circle cx="544.19" cy="337.28" r="1.08" fill="#6D604E" opacity="0.19" />
        <circle cx="67.25" cy="148.54" r="0.55" fill="#8A7C67" opacity="0.2" />
        <circle cx="352.24" cy="310.58" r="0.5" fill="#E6BA4E" opacity="0.23" />
        <circle cx="671.24" cy="228.19" r="0.52" fill="#E6BA4E" opacity="0.14" />
        <circle cx="55.08" cy="220.03" r="0.89" fill="#8A7C67" opacity="0.29" />
        <circle cx="31.48" cy="544.82" r="0.6" fill="#8A7C67" opacity="0.2" />
        <circle cx="375.98" cy="255.74" r="0.41" fill="#6D604E" opacity="0.13" />
        <circle cx="94.65" cy="247.51" r="0.84" fill="#8A7C67" opacity="0.31" />
        <circle cx="112.01" cy="176.36" r="0.49" fill="#8A7C67" opacity="0.15" />
        <circle cx="426.95" cy="474.49" r="0.51" fill="#6D604E" opacity="0.21" />
        <circle cx="199.06" cy="140.64" r="0.5" fill="#E6BA4E" opacity="0.19" />
        <circle cx="25.95" cy="470.06" r="0.92" fill="#8A7C67" opacity="0.21" />
        <circle cx="268.32" cy="65.36" r="1.13" fill="#E6BA4E" opacity="0.17" />
        <circle cx="637.86" cy="124.32" r="0.96" fill="#E6BA4E" opacity="0.3" />
        <circle cx="584.64" cy="492.18" r="0.97" fill="#6D604E" opacity="0.21" />
        <circle cx="567.85" cy="543.23" r="0.48" fill="#8A7C67" opacity="0.21" />
        <circle cx="273.81" cy="140.74" r="0.88" fill="#8A7C67" opacity="0.17" />
        <circle cx="182.26" cy="92.81" r="0.36" fill="#8A7C67" opacity="0.12" />
        <circle cx="435.48" cy="546.81" r="0.52" fill="#8A7C67" opacity="0.12" />
        <circle cx="620.18" cy="43.58" r="0.59" fill="#6D604E" opacity="0.11" />
        <circle cx="427.11" cy="348.73" r="0.7" fill="#8A7C67" opacity="0.21" />
        <circle cx="497.58" cy="498.47" r="0.7" fill="#8A7C67" opacity="0.23" />
        <circle cx="611.63" cy="492.15" r="0.95" fill="#8A7C67" opacity="0.25" />
        <circle cx="493.09" cy="509.97" r="0.84" fill="#E6BA4E" opacity="0.3" />
        <circle cx="547.47" cy="534.72" r="0.72" fill="#E6BA4E" opacity="0.39" />
        <circle cx="468.02" cy="519.53" r="0.7" fill="#6D604E" opacity="0.21" />
        <circle cx="538.85" cy="504.75" r="0.71" fill="#8A7C67" opacity="0.17" />
        <circle cx="418.88" cy="301.1" r="0.75" fill="#8A7C67" opacity="0.32" />
        <circle cx="270.05" cy="121.34" r="0.46" fill="#8A7C67" opacity="0.11" />
        <circle cx="77.21" cy="479.36" r="0.38" fill="#8A7C67" opacity="0.14" />
        <circle cx="199.56" cy="139.8" r="0.84" fill="#6D604E" opacity="0.23" />
        <circle cx="515.5" cy="283.64" r="0.48" fill="#6D604E" opacity="0.2" />
        <circle cx="340.32" cy="434.71" r="0.92" fill="#6D604E" opacity="0.28" />
        <circle cx="282.21" cy="121.81" r="0.53" fill="#8A7C67" opacity="0.24" />
        <circle cx="527.68" cy="61.77" r="0.86" fill="#8A7C67" opacity="0.27" />
        <circle cx="238.24" cy="514.81" r="0.98" fill="#8A7C67" opacity="0.22" />
        <circle cx="495.24" cy="505.94" r="0.51" fill="#E6BA4E" opacity="0.15" />
        <circle cx="111.66" cy="248.3" r="0.72" fill="#E6BA4E" opacity="0.28" />
        <circle cx="575.61" cy="465.33" r="0.83" fill="#6D604E" opacity="0.24" />
        <circle cx="549.79" cy="128.66" r="1.15" fill="#8A7C67" opacity="0.18" />
        <circle cx="514.4" cy="533.02" r="0.44" fill="#6D604E" opacity="0.22" />
        <circle cx="15.98" cy="336.67" r="1.01" fill="#8A7C67" opacity="0.38" />
        <circle cx="90.79" cy="391.94" r="0.45" fill="#6D604E" opacity="0.17" />
        <circle cx="573.85" cy="97.52" r="0.77" fill="#8A7C67" opacity="0.26" />
        <circle cx="612.48" cy="461.17" r="0.56" fill="#8A7C67" opacity="0.19" />
        <circle cx="608.6" cy="354.74" r="0.77" fill="#8A7C67" opacity="0.36" />
        <circle cx="616.01" cy="72.49" r="1.11" fill="#E6BA4E" opacity="0.23" />
        <circle cx="465.81" cy="297.24" r="0.82" fill="#8A7C67" opacity="0.23" />
        <circle cx="633.18" cy="394.16" r="0.85" fill="#E6BA4E" opacity="0.42" />
        <circle cx="61.09" cy="60.28" r="0.54" fill="#6D604E" opacity="0.11" />
        <circle cx="522.21" cy="243.17" r="0.36" fill="#8A7C67" opacity="0.11" />
        <circle cx="191.93" cy="222.24" r="0.87" fill="#6D604E" opacity="0.29" />
        <circle cx="40.72" cy="358.67" r="0.88" fill="#6D604E" opacity="0.2" />
        <circle cx="663.87" cy="294.37" r="0.78" fill="#6D604E" opacity="0.38" />
        <circle cx="265.95" cy="477.92" r="1.14" fill="#8A7C67" opacity="0.25" />
        <circle cx="126.8" cy="538.69" r="0.88" fill="#8A7C67" opacity="0.17" />
        <circle cx="157.27" cy="483.5" r="0.93" fill="#6D604E" opacity="0.38" />
        <circle cx="417.48" cy="251.24" r="0.7" fill="#8A7C67" opacity="0.25" />
        <circle cx="447.99" cy="75.83" r="1.03" fill="#6D604E" opacity="0.34" />
        <circle cx="169.11" cy="495.99" r="0.45" fill="#E6BA4E" opacity="0.11" />
        <circle cx="28.89" cy="21" r="1.15" fill="#6D604E" opacity="0.36" />
        <circle cx="414.52" cy="108.73" r="0.41" fill="#6D604E" opacity="0.18" />
        <circle cx="602.69" cy="520.52" r="0.56" fill="#6D604E" opacity="0.16" />
        <circle cx="640.94" cy="217.95" r="0.39" fill="#E6BA4E" opacity="0.13" />
        <circle cx="670.61" cy="451.36" r="0.52" fill="#8A7C67" opacity="0.12" />
      </g>

      <g className="oc-arcs" fill="none" stroke="#F0D07B" strokeWidth="0.9" strokeLinecap="round">
        <path d="M 137.77 373.52 A 222.98 222.98 0 0 1 130.64 352.61" opacity="0.23" />
        <path d="M 120.09 324.05 A 227.3 227.3 0 0 1 117.71 293.28" opacity="0.23" />
        <path d="M 134.75 234.69 A 217.71 217.71 0 0 1 146.97 200.74" opacity="0.33" />
        <path d="M 159.68 174.81 A 218.84 218.84 0 0 1 172.89 156.04" opacity="0.44" />
        <path d="M 186.83 137.51 A 220.54 220.54 0 0 1 203.46 122.07" opacity="0.35" />
        <path d="M 222.63 106.63 A 221.45 221.45 0 0 1 241.3 95.53" opacity="0.42" />
        <path d="M 264.02 78.79 A 227.32 227.32 0 0 1 283.34 72.4" opacity="0.31" />
        <path d="M 310.28 68.93 A 224.97 224.97 0 0 1 344.39 66.23" opacity="0.3" />
        <path d="M 372.28 69.13 A 223.74 223.74 0 0 1 393.53 72.78" opacity="0.31" />
        <path d="M 423.05 82.1 A 223.19 223.19 0 0 1 454.99 97" opacity="0.32" />
        <path d="M 474.26 116.93 A 216.97 216.97 0 0 1 484.22 124.78" opacity="0.21" />
        <path d="M 506.27 139.06 A 221.71 221.71 0 0 1 530.92 170.41" opacity="0.24" />
        <path d="M 546.71 196.99 A 222.62 222.62 0 0 1 555.02 217.36" opacity="0.18" />
      </g>

      <g className="oc-stars">
        <g className="oc-star oc-star--quiet" style={{ '--oc-i': 0, '--oc-d': '9.57s' } as CSSProperties}>
          <g opacity="0.75">
            <circle cx="146.28" cy="388.12" r="11.11" fill="url(#oh-h-quiet)" />
            <circle cx="146.28" cy="388.12" r="1.59" fill="#F0D07B" opacity="0.55" />
          </g>
        </g>
        <g className="oc-star oc-star--second" style={{ '--oc-i': 1, '--oc-d': '8.63s' } as CSSProperties}>
          <g opacity="0.81">
            <circle cx="124.77" cy="336.61" r="15.08" fill="url(#oh-h-second)" />
            <g stroke="#F7E4A9" strokeWidth="1.1" strokeLinecap="round" opacity="0.5">
              <line x1="118.53" y1="336.61" x2="131.01" y2="336.61" />
              <line x1="124.77" y1="330.37" x2="124.77" y2="342.85" />
            </g>
            <circle cx="124.77" cy="336.61" r="2.77" fill="#F7E4A9" opacity="1" />
          </g>
        </g>
        <g className="oc-star oc-star--quiet" style={{ '--oc-i': 2, '--oc-d': '7.92s' } as CSSProperties}>
          <g opacity="0.86">
            <circle cx="115.54" cy="279.91" r="11.49" fill="url(#oh-h-quiet)" />
            <circle cx="115.54" cy="279.91" r="1.72" fill="#F0D07B" opacity="0.88" />
          </g>
        </g>
        <g className="oc-star oc-star--quiet" style={{ '--oc-i': 3, '--oc-d': '6.78s' } as CSSProperties}>
          <g opacity="0.91">
            <circle cx="129.59" cy="248.76" r="12.17" fill="url(#oh-h-quiet)" />
            <circle cx="129.59" cy="248.76" r="1.95" fill="#F0D07B" opacity="0.54" />
            <circle cx="142.45" cy="250.06" r="0.59" fill="#F0D07B" opacity="0.27" />
          </g>
        </g>
        <g className="oc-star oc-star--quiet" style={{ '--oc-i': 4, '--oc-d': '7.42s' } as CSSProperties}>
          <g opacity="0.95">
            <circle cx="155.2" cy="188.36" r="12.1" fill="url(#oh-h-quiet)" />
            <circle cx="155.2" cy="188.36" r="1.93" fill="#F0D07B" opacity="0.68" />
          </g>
        </g>
        <g className="oc-star oc-star--focal" style={{ '--oc-i': 5, '--oc-d': '10.02s' } as CSSProperties}>
          <g opacity="1">
            <circle cx="179.72" cy="143.29" r="26" fill="url(#oh-h-focal)" />
            <g stroke="#F7E4A9" strokeWidth="1.5" strokeLinecap="round" opacity="0.85">
              <line x1="166.72" y1="143.29" x2="192.72" y2="143.29" />
              <line x1="179.72" y1="130.29" x2="179.72" y2="156.29" />
            </g>
            <circle cx="179.72" cy="143.29" r="4.5" fill="#FBF1D4" opacity="1" />
          </g>
        </g>
        <g className="oc-star oc-star--quiet" style={{ '--oc-i': 6, '--oc-d': '10.09s' } as CSSProperties}>
          <g opacity="0.95">
            <circle cx="211.3" cy="117.4" r="11.88" fill="url(#oh-h-quiet)" />
            <circle cx="211.3" cy="117.4" r="1.86" fill="#F0D07B" opacity="0.6" />
          </g>
        </g>
        <g className="oc-star oc-star--quiet" style={{ '--oc-i': 7, '--oc-d': '9.64s' } as CSSProperties}>
          <g opacity="0.91">
            <circle cx="254.41" cy="86.74" r="12.76" fill="url(#oh-h-quiet)" />
            <circle cx="254.41" cy="86.74" r="2.16" fill="#F0D07B" opacity="0.87" />
          </g>
        </g>
        <g className="oc-star oc-star--quiet" style={{ '--oc-i': 8, '--oc-d': '8.02s' } as CSSProperties}>
          <g opacity="0.86">
            <circle cx="294.17" cy="65.84" r="10.89" fill="url(#oh-h-quiet)" />
            <circle cx="294.17" cy="65.84" r="1.52" fill="#F0D07B" opacity="0.89" />
          </g>
        </g>
        <g className="oc-star oc-star--second" style={{ '--oc-i': 9, '--oc-d': '11.29s' } as CSSProperties}>
          <g opacity="0.81">
            <circle cx="359.05" cy="72.73" r="15.08" fill="url(#oh-h-second)" />
            <g stroke="#F7E4A9" strokeWidth="1.1" strokeLinecap="round" opacity="0.5">
              <line x1="352.81" y1="72.73" x2="365.29" y2="72.73" />
              <line x1="359.05" y1="66.49" x2="359.05" y2="78.97" />
            </g>
            <circle cx="359.05" cy="72.73" r="2.87" fill="#F7E4A9" opacity="1" />
          </g>
        </g>
        <g className="oc-star oc-star--quiet" style={{ '--oc-i': 10, '--oc-d': '8.54s' } as CSSProperties}>
          <g opacity="0.75">
            <circle cx="407.42" cy="71.33" r="12.41" fill="url(#oh-h-quiet)" />
            <circle cx="407.42" cy="71.33" r="2.04" fill="#F0D07B" opacity="0.86" />
            <circle cx="415.57" cy="67.13" r="0.66" fill="#F0D07B" opacity="0.22" />
          </g>
        </g>
        <g className="oc-star oc-star--quiet" style={{ '--oc-i': 11, '--oc-d': '6.96s' } as CSSProperties}>
          <g opacity="0.7">
            <circle cx="467.26" cy="110.94" r="10.33" fill="url(#oh-h-quiet)" />
            <circle cx="467.26" cy="110.94" r="1.32" fill="#F0D07B" opacity="0.6" />
            <circle cx="466.09" cy="106.08" r="0.71" fill="#F0D07B" opacity="0.32" />
          </g>
        </g>
        <g className="oc-star oc-star--quiet" style={{ '--oc-i': 12, '--oc-d': '7.55s' } as CSSProperties}>
          <g opacity="0.64">
            <circle cx="490.55" cy="131.43" r="11.75" fill="url(#oh-h-quiet)" />
            <circle cx="490.55" cy="131.43" r="1.81" fill="#F0D07B" opacity="0.59" />
          </g>
        </g>
        <g className="oc-star oc-star--second" style={{ '--oc-i': 13, '--oc-d': '7.28s' } as CSSProperties}>
          <g opacity="0.57">
            <circle cx="544.41" cy="182.13" r="15.08" fill="url(#oh-h-second)" />
            <g stroke="#F7E4A9" strokeWidth="1.1" strokeLinecap="round" opacity="0.5">
              <line x1="538.17" y1="182.13" x2="550.65" y2="182.13" />
              <line x1="544.41" y1="175.89" x2="544.41" y2="188.37" />
            </g>
            <circle cx="544.41" cy="182.13" r="2.18" fill="#F7E4A9" opacity="1" />
          </g>
        </g>
        <g className="oc-star oc-star--quiet" style={{ '--oc-i': 14, '--oc-d': '11.01s' } as CSSProperties}>
          <g opacity="0.49">
            <circle cx="554.8" cy="232.12" r="11.13" fill="url(#oh-h-quiet)" />
            <circle cx="554.8" cy="232.12" r="1.6" fill="#F0D07B" opacity="0.89" />
          </g>
        </g>
        <g className="oc-star oc-star--quiet" style={{ '--oc-i': 15, '--oc-d': '9.86s' } as CSSProperties}>
          <g opacity="0.36">
            <circle cx="565.94" cy="267.98" r="10.45" fill="url(#oh-h-quiet)" />
            <circle cx="565.94" cy="267.98" r="1.36" fill="#F0D07B" opacity="0.76" />
          </g>
        </g>
      </g>
    </svg>
  )
}
