// AUTO-GENERATED by scripts/gen-starfield.mjs — do not edit by hand.
// Thin dust field behind the page. No arcs, no bright stars — the halo
// constellation is the only thing that reads as a constellation.

export default function StarField({ className }: { className?: string }) {
  return (
    <svg
      className={className}
      viewBox="0 0 1440 900"
      preserveAspectRatio="xMidYMid slice"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden="true"
      focusable="false"
    >
      <circle cx="786.25" cy="560.53" r="0.73" fill="#8A7C67" opacity="0.23" />
      <circle cx="318.25" cy="809.16" r="1.09" fill="#D0C4AB" opacity="0.31" />
      <circle cx="546.16" cy="41.24" r="0.78" fill="#8A7C67" opacity="0.32" />
      <circle cx="236.35" cy="644.93" r="0.78" fill="#E6BA4E" opacity="0.36" />
      <circle cx="1391.18" cy="191.09" r="0.7" fill="#E6BA4E" opacity="0.25" />
      <circle cx="532.13" cy="66.95" r="1.17" fill="#E6BA4E" opacity="0.32" />
      <circle cx="1372.88" cy="835.15" r="0.97" fill="#8A7C67" opacity="0.24" />
      <circle cx="449.18" cy="583.11" r="0.73" fill="#E6BA4E" opacity="0.22" />
      <circle cx="1021.88" cy="36.66" r="0.65" fill="#8A7C67" opacity="0.26" />
      <circle cx="196.63" cy="287.4" r="1.19" fill="#8A7C67" opacity="0.25" />
      <circle cx="360.53" cy="453.23" r="0.95" fill="#8A7C67" opacity="0.33" />
      <circle cx="76.69" cy="162.19" r="0.62" fill="#D0C4AB" opacity="0.11" />
      <circle cx="1362.73" cy="301.51" r="0.64" fill="#8A7C67" opacity="0.32" />
      <circle cx="526.24" cy="874.29" r="0.62" fill="#D0C4AB" opacity="0.44" />
      <circle cx="231.55" cy="106.66" r="0.63" fill="#E6BA4E" opacity="0.39" />
      <circle cx="1100.16" cy="621.13" r="0.94" fill="#E6BA4E" opacity="0.2" />
      <circle cx="1016.96" cy="73.95" r="0.74" fill="#8A7C67" opacity="0.11" />
      <circle cx="384.86" cy="247.18" r="0.66" fill="#E6BA4E" opacity="0.29" />
      <circle cx="569.3" cy="289.99" r="0.81" fill="#8A7C67" opacity="0.17" />
      <circle cx="951.25" cy="74.56" r="0.7" fill="#8A7C67" opacity="0.32" />
      <circle cx="389.31" cy="766.4" r="0.86" fill="#D0C4AB" opacity="0.11" />
      <circle cx="640.99" cy="8.21" r="0.99" fill="#8A7C67" opacity="0.17" />
      <circle cx="808.21" cy="868.34" r="1.21" fill="#8A7C67" opacity="0.36" />
      <circle cx="1125.94" cy="724.54" r="0.71" fill="#8A7C67" opacity="0.14" />
      <circle cx="556.84" cy="808.69" r="0.95" fill="#8A7C67" opacity="0.4" />
      <circle cx="1337.58" cy="610.06" r="1.03" fill="#8A7C67" opacity="0.13" />
      <circle cx="1094.78" cy="654.45" r="0.63" fill="#8A7C67" opacity="0.43" />
      <circle cx="685.29" cy="594.78" r="0.87" fill="#D0C4AB" opacity="0.31" />
      <circle cx="26.31" cy="203.43" r="1.1" fill="#E6BA4E" opacity="0.33" />
      <circle cx="791.42" cy="314.62" r="0.81" fill="#D0C4AB" opacity="0.14" />
      <circle cx="143.56" cy="814.39" r="0.71" fill="#8A7C67" opacity="0.14" />
      <circle cx="414.73" cy="333.34" r="0.88" fill="#E6BA4E" opacity="0.22" />
      <circle cx="1438.24" cy="118.49" r="0.72" fill="#D0C4AB" opacity="0.41" />
      <circle cx="406.5" cy="365.88" r="1.11" fill="#D0C4AB" opacity="0.23" />
      <circle cx="543.59" cy="105.25" r="1.12" fill="#8A7C67" opacity="0.22" />
      <circle cx="873.76" cy="332.15" r="1.16" fill="#8A7C67" opacity="0.16" />
      <circle cx="340.65" cy="762.41" r="0.7" fill="#E6BA4E" opacity="0.29" />
      <circle cx="235.55" cy="352.85" r="1.02" fill="#8A7C67" opacity="0.44" />
      <circle cx="310.14" cy="123.59" r="0.86" fill="#E6BA4E" opacity="0.22" />
      <circle cx="54.84" cy="604.71" r="0.99" fill="#8A7C67" opacity="0.26" />
      <circle cx="275.19" cy="266.67" r="0.76" fill="#D0C4AB" opacity="0.23" />
      <circle cx="1315.89" cy="5.37" r="1.07" fill="#E6BA4E" opacity="0.23" />
      <circle cx="123.89" cy="494.02" r="1.12" fill="#D0C4AB" opacity="0.1" />
      <circle cx="1037.5" cy="650.27" r="1.03" fill="#8A7C67" opacity="0.33" />
      <circle cx="1073.54" cy="675.91" r="0.98" fill="#8A7C67" opacity="0.13" />
      <circle cx="27.73" cy="462.56" r="1.13" fill="#8A7C67" opacity="0.18" />
      <circle cx="1067.71" cy="670.75" r="0.97" fill="#8A7C67" opacity="0.3" />
      <circle cx="270.58" cy="6.09" r="0.71" fill="#D0C4AB" opacity="0.12" />
      <circle cx="157.48" cy="202.09" r="1.18" fill="#D0C4AB" opacity="0.37" />
      <circle cx="703.85" cy="70.9" r="0.55" fill="#E6BA4E" opacity="0.18" />
      <circle cx="1149.25" cy="439.31" r="0.76" fill="#8A7C67" opacity="0.15" />
      <circle cx="62.78" cy="401.47" r="0.84" fill="#D0C4AB" opacity="0.26" />
      <circle cx="120.07" cy="757.85" r="0.88" fill="#E6BA4E" opacity="0.37" />
      <circle cx="152.32" cy="231.83" r="0.87" fill="#E6BA4E" opacity="0.2" />
      <circle cx="117.15" cy="328.51" r="1.23" fill="#D0C4AB" opacity="0.34" />
      <circle cx="58.17" cy="647.37" r="0.78" fill="#D0C4AB" opacity="0.2" />
      <circle cx="1259.72" cy="687.89" r="1.03" fill="#8A7C67" opacity="0.26" />
      <circle cx="398.78" cy="440.67" r="0.99" fill="#8A7C67" opacity="0.33" />
      <circle cx="985.49" cy="893.65" r="0.97" fill="#8A7C67" opacity="0.39" />
      <circle cx="608.1" cy="46.5" r="1.01" fill="#8A7C67" opacity="0.16" />
      <circle cx="768.61" cy="843.35" r="0.77" fill="#8A7C67" opacity="0.32" />
      <circle cx="471.65" cy="258.69" r="0.62" fill="#E6BA4E" opacity="0.39" />
      <circle cx="1221.6" cy="78.95" r="0.61" fill="#D0C4AB" opacity="0.21" />
      <circle cx="1428.03" cy="683.63" r="0.89" fill="#8A7C67" opacity="0.18" />
      <circle cx="176.56" cy="313.34" r="0.92" fill="#D0C4AB" opacity="0.24" />
      <circle cx="1103.43" cy="150.44" r="1.1" fill="#8A7C67" opacity="0.19" />
      <circle cx="634.49" cy="867.3" r="1" fill="#D0C4AB" opacity="0.22" />
      <circle cx="1234.93" cy="451.41" r="1.16" fill="#8A7C67" opacity="0.29" />
      <circle cx="560.76" cy="518.06" r="0.92" fill="#D0C4AB" opacity="0.17" />
      <circle cx="1042.79" cy="178.23" r="0.83" fill="#8A7C67" opacity="0.13" />
      <circle cx="383.95" cy="108.25" r="1.15" fill="#E6BA4E" opacity="0.11" />
      <circle cx="940.7" cy="116.75" r="1.15" fill="#8A7C67" opacity="0.25" />
      <circle cx="1418.07" cy="193.12" r="0.68" fill="#8A7C67" opacity="0.39" />
      <circle cx="1112.36" cy="490.12" r="0.67" fill="#E6BA4E" opacity="0.21" />
    </svg>
  )
}
